apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-backend
  namespace: movie-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-backend
  template:
    metadata:
      labels:
        app: movie-backend
    spec:
      containers:
      - name: movie-backend
        image: <your-backend-image>:latest  # Replace with your actual image name
        env:
        - name: DATABASE_URL
          value: postgresql://admin:admin123@postgres:5432/movies_db
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: movie-backend
  namespace: movie-admin
spec:
  type: NodePort
  selector:
    app: movie-backend
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
